version: "2"
run:
  concurrency: 4
  issues-exit-code: 20
  tests: true
linters:
  enable:
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - lll
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - govet
    - staticcheck
    - unused
    - ineffassign
    - errcheck
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 17
    lll:
      line-length: 120
      tab-width: 1
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    govet:
      check-shadowing: true
    errcheck:
      check-type-assertions: true
      check-blank: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$