name: Test

on:
  push:

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.x

    - name: Test
      run: make
